// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfabrnzppzorywipiwcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmYWJybnpwcHpvcnl3aXBpd2NtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDg5MDIsImV4cCI6MjA2Mzg4NDkwMn0.RebRfMuCwkUJOf9PfxwymUQ4gWvT7nqzRg3B9ftAojg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);